services:

  db:
    container_name: backend_db
    build:
      context: ./
      dockerfile: ./docker/local/db.dockerfile
    networks:
      backend_db_network:
        aliases:
          - backend_db
    ports:
      - '${DOCKER_DB_PORT}:3306'
    volumes:
      - backend_db_mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # restart: always

  app:
    restart: always
    container_name: backend_api
    # image: ${DOCKER_APP_IMAGE}
    build:
      context: ./
      dockerfile: ./docker/local/app.dockerfile
    env_file:
      - ./.env
    networks:
      backend_db_network:
        aliases:
          - backend_api
    ports:
      - '${DOCKER_APP_PORT}:80'
    environment:
      - APP_ENV
      - APP_KEY
      - APP_URL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - JWT_SECRET
      - DOCKER_DB_PORT
      - PORT
      - DOCKER_APP_PORT
      
    depends_on:
      - db

networks:
  backend_db_network:
    external: true
    name: backend_test

volumes:
  backend_db_mysql_data:
    external: false